version: 2
updates:
  - package-ecosystem: "mix"
    directory: "/"
    open-pull-requests-limit: 1
    reviewers:
      - "shymega"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps)"
    groups:
      mix-deps:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(ci-deps)"
    groups:
      gh-actions-deps:
        patterns:
          - "*"
